### ISSUE TITLE
Create line plot

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#19]
Generate a simple line plot with x, and y-axes, support for multiple lines, utilizing Plotly to generate interactivity.  

- [x] Basic functionality
- [x] add y2 axis
- [x] add x2 axis
- [x] add STD CI
- [x] add point symbols, series line types, line type, line width
- [x] add 'show significant' - **CAN'T IMPLEMENT USING Plotly**
- [x] add connect across N/A
- [x] add grouping
- [x] add all parameters from the 'Common' section
- [x] add derived curves
- [x] add sum/agg stats
- [x] add sum/agg stats derived curves
- [x] add series reordering
- [x] use indy_labels for x-axis
- [x] Axis Margin Line parameters - **CAN'T IMPLEMENT USING Plotly**
- [x] x-axis limits - **CAN'T IMPLEMENT USING Plotly**
- [x] axis values formatting - Perpendicular offset, Frequency, Horizontal align**CAN'T IMPLEMENT USING Plotly**
- [x]  caption and caption formatting
- [x] add create HTML functionality and a config parameter
- [x] update line_defaults.yaml with all new parameters
- [x] implement and add scaleStats functionality **??? - currently UI doesn't have this option - not sure it needed**

**Comment by TatianaBurek** [comment]
NOTE:
There is no point to have a separate parameters for **indy_stagger** for y1 and y2 axis. 
We need to join them to one. For now the code use indy_stagger_1 only

**Comment by TatianaBurek** [comment]
NOTE:
Can't implement '**show significant**' because Plotly doesn't support styling individual CI

**Comment by bikegeek** [comment]
incorporated in v1.0-beta1
