### ISSUE TITLE
x-axis labeling doesn't follow the order specified in independent Var

### ISSUE THREAD

**Issue by TatianaBurek** [dtcenter/METplotpy#218]
## Describe the Problem ##
If indy var is not a number the order in with the values are plotted  could be incorrect.For example,
XML:
[plot_20220404_140136.xml.txt](https://github.com/dtcenter/METplotpy/files/8410352/plot_20220404_140136.xml.txt)

YAML:
```
indy_label:
- <1.0
- '>1.0'
- '>2.0'
- '>5.0'
- '>10.0'
- '>15.0'
- '>20.0'
indy_vals:
- <1.0
- '>1.0'
- '>2.0'
- '>5.0'
- '>10.0'
- '>15.0'
- '>20.0'
```
But this is the plot with incorrect x-axis order:

![plot_20220404_140136](https://user-images.githubusercontent.com/21346768/161562742-ad1b2810-d133-486b-914e-9cfd30d62479.png)

Need to fix ordering string values
### Expected Behavior ###
x-values should be plotted exactly in the same order as in YAML

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by bikegeek** [comment]
I created some code back in 2021 that sorts a dataframe based on threshold values by leveraging pandas dataframe's ability to sort by n-columns, I applied a weight to the boolean operation (<,<=, ==, etc.) for one column and the numerical value for the second column.

**Comment by TatianaBurek** [comment]
[plot_20230329_220359.yaml.txt](https://github.com/dtcenter/METplotpy/files/11105975/plot_20230329_220359.yaml.txt)
[plot_20230329_220359.data.txt](https://github.com/dtcenter/METplotpy/files/11105981/plot_20230329_220359.data.txt)

**Comment by bikegeek** [comment]
Tatiana, thank you!!!!


---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Research Applications Lab
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------
