### ISSUE TITLE
the CI's are oriented the wrong way in  a vertical levels plot

### ISSUE THREAD

**Issue by TatianaBurek** [dtcenter/METplotpy#219]
## Describe the Problem ##
When plotting a vertical levels plot, using python capabilities, the CI's are oriented the wrong way. They are fine with Rscript capabilities.
Python:
![plot_20220408_163210](https://user-images.githubusercontent.com/21346768/162484440-63b43dd9-caee-4ef5-9797-675e53f9110d.png)
Rscript:
![plot_20220408_163535](https://user-images.githubusercontent.com/21346768/162484553-5ff992af-ddec-4c57-bbc9-eba74a11dfc9.png)
XML:
[plot_20220408_163633.xml.txt](https://github.com/dtcenter/METplotpy/files/8453857/plot_20220408_163633.xml.txt)

### Expected Behavior ###
CIs should be oriented correctly on the Python vertical plot
### Environment ###

Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by bikegeek** [comment]
Check for the boolean value of 'vert_plot' in the yaml configuration file.  

If it is True, add some plotting logic (~after line 290) from 
error_y=

to error_x =

pseudo-code:

if config['vert_plot']:
     self.figure.add_trace(
            go.Scatter(x=x_points_index_adj,
                       y=y_points,
                       showlegend=True,
                       mode=self.config_obj.mode[series.idx],
                       textposition="top right",
                       name=self.config_obj.user_legends[series.idx],
                       connectgaps=self.config_obj.con_series[series.idx] == 1,
                       line={'color': self.config_obj.colors_list[series.idx],
                             'width': self.config_obj.linewidth_list[series.idx],
                             'dash': self.config_obj.linestyles_list[series.idx]},
                       marker_symbol=self.config_obj.marker_list[series.idx],
                       marker_color=self.config_obj.colors_list[series.idx],
                       marker_line_color=self.config_obj.colors_list[series.idx],
                       marker_size=self.config_obj.marker_size[series.idx],
                       **error_x**={'type': 'data',
                                'symmetric': False,
                                'array': series.series_points['dbl_up_ci'],
                                'arrayminus': series.series_points['dbl_lo_ci'],
                                'visible': error_y_visible,
                                'thickness': self.config_obj.linewidth_list[series.idx]}
                       ),



else:
    self.figure.add_trace(
            go.Scatter(x=x_points_index_adj,
                       y=y_points,
                       showlegend=True,
                       mode=self.config_obj.mode[series.idx],
                       textposition="top right",
                       name=self.config_obj.user_legends[series.idx],
                       connectgaps=self.config_obj.con_series[series.idx] == 1,
                       line={'color': self.config_obj.colors_list[series.idx],
                             'width': self.config_obj.linewidth_list[series.idx],
                             'dash': self.config_obj.linestyles_list[series.idx]},
                       marker_symbol=self.config_obj.marker_list[series.idx],
                       marker_color=self.config_obj.colors_list[series.idx],
                       marker_line_color=self.config_obj.colors_list[series.idx],
                       marker_size=self.config_obj.marker_size[series.idx],
                       **error_y**={'type': 'data',
                                'symmetric': False,
                                'array': series.series_points['dbl_up_ci'],
                                'arrayminus': series.series_points['dbl_lo_ci'],
                                'visible': error_y_visible,
                                'thickness': self.config_obj.linewidth_list[series.idx]}
                       ),
