### ISSUE TITLE
Support plotting of TDF/GDF metrics for S2S METplus use cases

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplotpy#48]
## Describe the New Feature ##
Plot the TDF/GDF metrics from the METplus use cases (dtcenter/METplus#630, dtcenter/METplus#631).

The plot will be a contour plot, of type raster or "cell" filling, on a global latitude/longitude domain. There could be multiple panels. Types of panels include:
1. Total count of all observed genesis events
2. Total count of all forecasted genesis events
3. Total count of all hits
4. Total count of all misses
5. Total count of all false alarms
6. Total count of all track points within the grid cell

### Acceptance Testing ###
- [ ] User configurable latitude bounds
- [ ] User configurable number of panels/panel order
- [ ] User configurable title strings per panel

### Time Estimate ###
2-4 days of work.

### Funding Source ###
UIUC S2S 7790971

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
I am working in a branch:
`feature_48_s2s_tdf_gdf`

I created a conda environment for this work, copied from the met_test user on kiowa:
`conda create --name s2stc --clone /home/met_test/.conda/envs/metplus_dev`

I installed METplotpy by cloning and adding to my conda env:
```
git clone git@github.com/dtcenter/METplotpy
cd METplotpy
pip install -e .
```

I created a new directory here where I will work:
`METplotpy/metplotpy/contributed/tc_s2s_panel`

**Comment by DanielAdriaansen** [comment]
@bikegeek what's the preferred way to import my functions?

If my script lives in:
`METplotpy/metplotpy/contributed/tc_s2s_panel/plot_tc_s2s_panel.py`

What would an import statement look like? Does `plot_tc_s2s_panel.py` have to conform to some Python standard in order to be "importable"?

**Comment by bikegeek** [comment]
I forgot to mention that you will need to create an empty file: __init__.py
in the directory where your module (that you wish to import) resides.  So
in METplotpy/metplotpy/contributed/tc_s2s_panel, add a __init__py (and in
any subdirectories you create under the tc_s2s_panel).  This signals to
Python that these modules can be imported.

Then, to import:
from metplotpy.contributed.tc_s2s_panel import plot_tc_s2s_panel as
tc_panel

or

from metplotpy.contributed.tc_s2s_panel import plot_tc_s2s_panel

if you don't like aliases.








---------------
Minna Win
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------
Pronouns: she/her
