### ISSUE TITLE
Differences on series naming and ordering between Rscript and Python

### ISSUE THREAD

**Issue by TatianaBurek** [dtcenter/METplotpy#59]
## Describe the Problem ##
*These images looks different - series names and order
![plot_20201027_202950](https://user-images.githubusercontent.com/21346768/97359136-e81c5f80-1861-11eb-8451-cfcafad5a8c4.png)
![plot_20201027_203008](https://user-images.githubusercontent.com/21346768/97359143-ea7eb980-1861-11eb-9aaf-850e592c5053.png)
*

### Expected Behavior ###
*Plots should be identical*

### To Reproduce ###
[plot_20201027_203008.xml.txt](https://github.com/dtcenter/METviewer/files/5448011/plot_20201027_203008.xml.txt)

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to relevant bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by TatianaBurek** [comment]
list(itertools.product(*all_fields_values.values())) doesn't create permutations in the order like METviewer does. Needs to be replaced with a custom function
https://github.com/dtcenter/METcalcpy/tree/issue/44-series_permutations

**Comment by bikegeek** [comment]
This was fixed in Github Issue #12
