### ISSUE TITLE
Difficulty index plot loses data at edges

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplotpy#76]
The difficulty index script uses a matplotlib call that fails unless it is using matplotlib 2.2.2.

https://github.com/dtcenter/METplotpy/blob/041a9b0f8c63e4153473433130c29d1cb8a429fb/metplotpy/plots/difficulty_index/plot_difficulty_index.py#L64

However, it looks like the shading method is actually not a valid value. The default value of "flat" is being used. Running with this configuration in the latest version of matplotlib (3.3.3) throws a warning:

```
/root/matplotlib/examples/images_contours_and_fields/pcolormesh_grids.py:66: MatplotlibDeprecationWarning: shading='flat' when X and Y have the same dimensions as C is deprecated since 3.3.  Either specify the corners of the quadrilaterals with X and Y, or pass shading='auto', 'nearest' or 'gouraud', or set rcParams['pcolor.shading'].  This will become an error two minor releases later.
  ax.pcolormesh(x, y, Z, shading='flat', vmin=Z.min(), vmax=Z.max())
```

The old behavior (before 3.3) is to silently remove the last row and column of data from the grid when running this way.
See this link for more information: https://matplotlib.org/3.3.3/gallery/images_contours_and_fields/pcolormesh_grids.html#flat-shading-same-shape-grid

## Describe the Problem ##
We want to remove the dependency on matplotlib 2.2.2 and fix the problematic function call so that it uses an approach that is not deprecated and results in losing data.

### Expected Behavior ###
Be able to run METplotpy using the latest matplotlib version (3.3.3) without error.

### Environment ###
A Python environment using matplotlib 3.3.3 and scipy are needed to test. The pytest in question is:
METplotpy/test/difficulty_index/test_difficulty_index_plotting.py

### To Reproduce ###
Set up the environment above and run the pytest listed.

### Relevant Deadlines ###
None

### Funding Source ###
2700021

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to relevant bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [X] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>` DON'T NEED TO APPLY TO MAIN BRANCH
- [X] Fix the bug and test your changes.
- [X] Add/update log messages for easier debugging.
- [X] Add/update unit tests.
- [X] Add/update documentation.
- [X] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by lindsayrblank** [comment]
I am waiting to hear back from Bill and Liz of NRL about this change before approval.
